import os
import json
import asyncio
import websockets
import time
import logging
from confluent_kafka import Producer
from dotenv import load_dotenv

# Note: MarketDataFeedV3_pb2 is generated by 'protoc' in the Dockerfile CMD at startup
try:
    import MarketDataFeedV3_pb2 as pb
except ImportError:
    print("Warning: Protobuf classes not found. They will be generated at runtime.")

load_dotenv()

# Logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("Ingestor-V3-Greeks")

KAFKA_SERVER = os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'kafka_bus:9092')

async def connect_upstox_v3():
    # 1. WAIT FOR KAFKA
    producer = None
    logger.info(f"Connecting to Kafka at {KAFKA_SERVER}...")
    while producer is None:
        try:
            p = Producer({'bootstrap.servers': KAFKA_SERVER, 'socket.timeout.ms': 1000})
            p.list_topics(timeout=1.0)
            producer = p
            logger.info("✅ Kafka is Online!")
        except Exception:
            logger.info("Kafka not ready, retrying...")
            await asyncio.sleep(2)

    # 2. CONFIGURATION
    uri = "wss://api.upstox.com/v3/feed/market-data-feed"
    token = os.getenv('UPSTOX_ACCESS_TOKEN', '').strip()
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "*/*",
        "Api-Version": "2.0"
    }

    # 3. QUANT SUBSCRIPTION LIST (Equity + Index + Volatility + Option)
    # Note: Option keys (NSE_FO) change weekly. Ensure this key is valid for current expiry.
    instruments = [
        "NSE_EQ|INE002A01018",   # Reliance (Stock)
        "NSE_INDEX|Nifty 50",     # Nifty (Market)
        "NSE_INDEX|India VIX",    # VIX (Fear)
        "NSE_FO|45450"           # Example Nifty Option for Greeks
    ]

    logger.info(f"Attempting Upstox V3 Connection...")
    
    try:
        # Handle websockets library version differences
        try:
            ws_conn = websockets.connect(uri, additional_headers=headers)
        except TypeError:
            ws_conn = websockets.connect(uri, extra_headers=headers)

        async with ws_conn as websocket:
            logger.info("🚀 SUCCESS: Connected to Upstox V3 Live Stream!")

            # Request subscription in 'full' mode to get Greeks & Depth
            sub_request = {
                "guid": f"quant_mac_{int(time.time())}",
                "method": "sub",
                "data": {
                    "mode": "full", 
                    "instrumentKeys": instruments
                }
            }
            
            await websocket.send(json.dumps(sub_request).encode('utf-8'))
            logger.info(f"Subscribed to {len(instruments)} instruments including Greeks.")

            # 4. BINARY DECODING LOOP
            async for message in websocket:
                if isinstance(message, bytes):
                    try:
                        import MarketDataFeedV3_pb2 as pb
                        res = pb.MarketDataFeed()
                        res.ParseFromString(message)
                        
                        for key, feed in res.feeds.items():
                            # A. Handle Price/Volume/OI Data (LTPC)
                            if feed.ltpc:
                                tick = {
                                    "symbol": key,
                                    "ltp": feed.ltpc.ltp,
                                    "v": feed.ltpc.ltq,
                                    "oi": feed.ltpc.oi,
                                    "cp": feed.ltpc.cp,
                                    "timestamp": int(time.time() * 1000)
                                }
                                producer.produce('market.equity.ticks', key=key, value=json.dumps(tick))
                                
                                # Conditional Logging
                                if "INDEX" in key:
                                    logger.info(f"Market Update -> {key}: {tick['ltp']}")

                            # B. Handle Option Greeks Data
                            if feed.greeks:
                                greeks = {
                                    "symbol": key,
                                    "iv": round(feed.greeks.iv, 4),
                                    "delta": round(feed.greeks.delta, 4),
                                    "gamma": round(feed.greeks.gamma, 4),
                                    "theta": round(feed.greeks.theta, 4),
                                    "vega": round(feed.greeks.vega, 4),
                                    "timestamp": int(time.time() * 1000)
                                }
                                producer.produce('market.option.greeks', key=key, value=json.dumps(greeks))
                                logger.info(f"Greeks -> {key}: Delta={greeks['delta']}, IV={greeks['iv']}")
                        
                        producer.poll(0) # Flush Kafka buffer

                    except Exception as decode_err:
                        logger.error(f"Protobuf Error: {decode_err}")
                else:
                    # Handle Heartbeats / Status
                    print(f"Server Message: {message}")

    except Exception as e:
        logger.error(f"V3 Connection Error: {e}")
        if "401" in str(e):
            logger.error("❌ TOKEN EXPIRED: Refresh UPSTOX_ACCESS_TOKEN in .env")
        await asyncio.sleep(10)

if __name__ == "__main__":
    try:
        asyncio.run(connect_upstox_v3())
    except KeyboardInterrupt:
        logger.info("Ingestor stopped.")