# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MarketDataFeedV3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MarketDataFeedV3.proto\x12\x18\x63om.upstox.marketdata.v3\"\xb5\x01\n\x0eMarketDataFeed\x12\x42\n\x05\x66\x65\x65\x64s\x18\x01 \x03(\x0b\x32\x33.com.upstox.marketdata.v3.MarketDataFeed.FeedsEntry\x12\x11\n\tcurrentTs\x18\x02 \x01(\x03\x1aL\n\nFeedsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.com.upstox.marketdata.v3.Feed:\x02\x38\x01\"4\n\x04\x46\x65\x65\x64\x12,\n\x04ltpc\x18\x01 \x01(\x0b\x32\x1e.com.upstox.marketdata.v3.LTPC\"9\n\x04LTPC\x12\x0b\n\x03ltp\x18\x01 \x01(\x01\x12\x0b\n\x03ltt\x18\x02 \x01(\x03\x12\x0b\n\x03ltq\x18\x03 \x01(\x03\x12\n\n\x02\x63p\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDataFeedV3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MARKETDATAFEED_FEEDSENTRY._options = None
  _MARKETDATAFEED_FEEDSENTRY._serialized_options = b'8\001'
  _MARKETDATAFEED._serialized_start=53
  _MARKETDATAFEED._serialized_end=234
  _MARKETDATAFEED_FEEDSENTRY._serialized_start=158
  _MARKETDATAFEED_FEEDSENTRY._serialized_end=234
  _FEED._serialized_start=236
  _FEED._serialized_end=288
  _LTPC._serialized_start=290
  _LTPC._serialized_end=347
# @@protoc_insertion_point(module_scope)
